import type { Question } from './types';

export const QUESTIONS: Question[] = [
  // Phase 0: Decision problem definition
  {
    id: '0.1',
    phase: 'phase0',
    section: '決策問題界定',
    text: '你正在考慮的決策是什麼？請用一句話描述。',
    purpose: '界定決策本身',
    inputType: 'text',
    placeholder: '例如：是否先在一個小區域試行新的管理流程？',
  },
  {
    id: '0.2',
    phase: 'phase0',
    section: '決策問題界定',
    text: '這個決策最晚何時需要做出？',
    purpose: '確認時間壓力',
    claims: ['C-002'],
    inputType: 'text',
    placeholder: '例如：下個月底前',
  },
  {
    id: '0.3',
    phase: 'phase0',
    section: '決策問題界定',
    text: '這個決策的範圍有多大？涉及哪些人、多少資源？',
    purpose: '評估賭注大小',
    claims: ['C-082'],
    inputType: 'textarea',
    placeholder: '描述影響範圍、涉及人數、資源規模…',
  },
  {
    id: '0.4',
    phase: 'phase0',
    section: '決策問題界定',
    text: '這個決策可逆嗎？如果做錯了，能回頭嗎？',
    purpose: '評估可逆性',
    inputType: 'select',
    options: ['可逆 — 容易回頭', '部分可逆 — 有一定成本', '不可逆 — 很難回頭'],
  },

  // Phase 1A: Intuition surfacing
  {
    id: '1.1',
    phase: 'phase1',
    section: 'Divergent — 直覺外顯',
    text: '你對這個決策的第一直覺是什麼？傾向 go 還是 stop？',
    purpose: '外顯 System 1 直覺',
    claims: ['C-001', 'C-002'],
    inputType: 'select',
    options: ['傾向 go', '傾向 stop', '還不確定'],
  },
  {
    id: '1.2',
    phase: 'phase1',
    section: 'Divergent — 直覺外顯',
    text: '這個直覺背後的故事是什麼？你腦中浮現了哪些畫面或案例？',
    purpose: '檢查 WYSIATI — System 1 用手頭資訊建構的故事',
    claims: ['C-005', 'C-006'],
    inputType: 'textarea',
    placeholder: '描述你腦中浮現的畫面、案例、情境…',
  },
  {
    id: '1.3',
    phase: 'phase1',
    section: 'Divergent — 直覺外顯',
    text: '你對這個直覺有多大的信心？（1-10 分）',
    purpose: '記錄主觀信心基線（注意：信心不等於準確性）',
    claims: ['C-006', 'C-023', 'C-069'],
    inputType: 'score',
  },
  {
    id: '1.4',
    phase: 'phase1',
    section: 'Divergent — 直覺外顯',
    text: '這個直覺讓你聯想到什麼情緒？',
    purpose: '記錄情緒信號',
    claims: ['C-009', 'C-010'],
    inputType: 'select',
    options: ['興奮', '恐懼', '焦慮', '安心', '無特別情緒'],
  },

  // Phase 1B: Assumptions and hypotheses
  {
    id: '1.5',
    phase: 'phase1',
    section: 'Divergent — 假設與假說列舉',
    text: '這個決策背後有哪些你還沒驗證的假設？',
    purpose: '列舉隱含假設',
    claims: ['C-005'],
    inputType: 'textarea',
    placeholder: '列出你假設為真但尚未驗證的前提…',
  },
  {
    id: '1.6',
    phase: 'phase1',
    section: 'Divergent — 假設與假說列舉',
    text: '如果這個決策成功了，你認為主要原因會是什麼？',
    purpose: '檢查敘事謬誤 — 成功故事常過度歸因才能而輕視運氣',
    claims: ['C-031'],
    inputType: 'textarea',
    placeholder: '你預期的成功因素…',
  },
  {
    id: '1.7',
    phase: 'phase1',
    section: 'Divergent — 假設與假說列舉',
    text: '是什麼讓你覺得這個方案可行？第一次聽到或想到它是什麼情境？',
    purpose: '檢查可得性 — 方案可能只是因為容易想到',
    claims: ['C-015', 'C-016'],
    inputType: 'textarea',
    placeholder: '方案來源、接觸情境…',
  },
  {
    id: '1.8',
    phase: 'phase1',
    section: 'Divergent — 假設與假說列舉',
    text: '有沒有一個數字或參考點一直盤據在你腦中？（例如預算上限、他人報價、歷史數據）',
    purpose: '檢查錨定 — 先前接觸的數字可能正在影響估計',
    claims: ['C-011', 'C-012'],
    inputType: 'textarea',
    placeholder: '影響你判斷的數字或參考點…',
  },
  {
    id: '1.9',
    phase: 'phase1',
    section: 'Divergent — 假設與假說列舉',
    text: '這個決策是怎麼被「框」起來的？如果換一個問法，你還會做同樣的選擇嗎？',
    purpose: '檢查框架效應',
    claims: ['C-048', 'C-050'],
    inputType: 'textarea',
    placeholder: '目前的框架是什麼？換成什麼問法？',
  },

  // Phase 2A: Evidence review
  {
    id: '2.1',
    phase: 'phase2',
    section: 'Convergent — 證據檢核',
    text: '你目前掌握了哪些「事實」？這些事實的來源是什麼？',
    purpose: '區分 fact 與 assumption',
    claims: ['C-005', 'C-008'],
    inputType: 'textarea',
    placeholder: '列出已知事實及其來源…',
  },
  {
    id: '2.2',
    phase: 'phase2',
    section: 'Convergent — 證據檢核',
    text: '你可能缺少哪些資訊？有哪些你知道自己不知道的？',
    purpose: '補強 WYSIATI 盲區',
    claims: ['C-005', 'C-008'],
    inputType: 'textarea',
    placeholder: '列出資訊缺口…',
  },
  {
    id: '2.3',
    phase: 'phase2',
    section: 'Convergent — 證據檢核',
    text: '這個決策是基於單一來源（一份報告、一個人的意見）嗎？',
    purpose: '檢查資訊來源多樣性',
    claims: ['C-008', 'C-021', 'C-022'],
    inputType: 'select',
    options: ['是 — 單一來源', '否 — 多元來源', '不確定'],
  },
  {
    id: '2.4',
    phase: 'phase2',
    section: 'Convergent — 證據檢核',
    text: '如果要你說服一個反對者，你會用什麼證據？',
    purpose: '測試證據強度',
    inputType: 'textarea',
    placeholder: '你最有力的證據是什麼…',
  },

  // Phase 2B: Base rate / outside view
  {
    id: '2.5',
    phase: 'phase2',
    section: 'Convergent — Base Rate / 外部視角',
    text: '在類似的情況下，別人的成功率是多少？（參考類別的基礎比率）',
    purpose: '引入外部視角',
    claims: ['C-032', 'C-034', 'C-036', 'C-038'],
    inputType: 'textarea',
    placeholder: '同類專案/決策的成功率、失敗率…',
  },
  {
    id: '2.6',
    phase: 'phase2',
    section: 'Convergent — Base Rate / 外部視角',
    text: '我們如何知道這一次跟參考類別不同？有什麼具體證據支持「這次不一樣」？',
    purpose: '檢查內部意見偏見',
    claims: ['C-035', 'C-036'],
    inputType: 'textarea',
    placeholder: '本案例與參考類別的差異及證據…',
  },
  {
    id: '2.7',
    phase: 'phase2',
    section: 'Convergent — Base Rate / 外部視角',
    text: '這個專案/計劃的時間和成本預估，是否參考了同類專案的分佈？還是只看最佳情境？',
    purpose: '檢查規劃謬誤',
    claims: ['C-037', 'C-039', 'C-040'],
    inputType: 'select',
    options: ['參考了同類分佈', '只看最佳情境', '兩者都有', '不確定'],
  },
  {
    id: '2.8',
    phase: 'phase2',
    section: 'Convergent — Base Rate / 外部視角',
    text: '如果證據薄弱，你是否應該回到基礎比率？',
    purpose: '證據薄弱時堅持 base rate',
    claims: ['C-034'],
    inputType: 'select',
    options: ['是 — 應回到基礎比率', '否 — 證據足夠', '不確定'],
  },

  // Phase 2C: Bias checklist
  {
    id: '2.9',
    phase: 'phase2',
    section: 'Convergent — 偏誤逐項檢查',
    text: '【錨定】有沒有一個數字不斷影響你的估計？你是否嘗試過從零開始重新估算？',
    purpose: '檢查錨定效應',
    claims: ['C-011', 'C-013'],
    inputType: 'textarea',
    placeholder: '可能的錨點、重新估算的結果…',
  },
  {
    id: '2.10',
    phase: 'phase2',
    section: 'Convergent — 偏誤逐項檢查',
    text: '【可得性】你想到的案例是因為它真的常見，還是因為它特別生動/最近發生？',
    purpose: '檢查可得性偏見',
    claims: ['C-015', 'C-017'],
    inputType: 'textarea',
    placeholder: '案例來源、生動程度、實際頻率…',
  },
  {
    id: '2.11',
    phase: 'phase2',
    section: 'Convergent — 偏誤逐項檢查',
    text: '【框架】如果把「獲利」改說成「避免損失」，或把「風險」改說成「機會」，你的決策會改變嗎？',
    purpose: '檢查框架效應',
    claims: ['C-048', 'C-049'],
    inputType: 'textarea',
    placeholder: '不同框架下的決策差異…',
  },
  {
    id: '2.12',
    phase: 'phase2',
    section: 'Convergent — 偏誤逐項檢查',
    text: '【過度自信】你對預測的信心是否高於應有水準？你有沒有考慮過自己可能錯在哪裡？',
    purpose: '檢查過度自信',
    claims: ['C-023', 'C-025', 'C-026'],
    inputType: 'textarea',
    placeholder: '可能的錯誤點、信心校準…',
  },
  {
    id: '2.13',
    phase: 'phase2',
    section: 'Convergent — 偏誤逐項檢查',
    text: '【確認偏誤】你是否主動尋找過反證？還是只在找支持自己方案的資料？',
    purpose: '檢查確認偏誤',
    claims: ['C-018', 'C-019'],
    inputType: 'textarea',
    placeholder: '反證搜尋紀錄…',
  },
  {
    id: '2.14',
    phase: 'phase2',
    section: 'Convergent — 偏誤逐項檢查',
    text: '【後見之明/結果偏誤】如果這個決策未來失敗了，你預期別人會怎麼評價你？這是否正在影響你現在的選擇？',
    purpose: '檢查後見之明壓力',
    claims: ['C-027', 'C-028', 'C-029'],
    inputType: 'textarea',
    placeholder: '預期的外部評價、對決策的影響…',
  },
  {
    id: '2.15',
    phase: 'phase2',
    section: 'Convergent — 偏誤逐項檢查',
    text: '【損失厭惡】你是否因為害怕失去現有資源/地位而拒絕一個值得冒險的方案？',
    purpose: '檢查損失厭惡',
    claims: ['C-052', 'C-055', 'C-066'],
    inputType: 'textarea',
    placeholder: '可能的損失厭惡影響…',
  },
  {
    id: '2.16',
    phase: 'phase2',
    section: 'Convergent — 偏誤逐項檢查',
    text: '【沉沒成本】你是否因為已經投入了時間/金錢而難以放棄？',
    purpose: '檢查沉沒成本謬誤',
    claims: ['C-059', 'C-060'],
    inputType: 'textarea',
    placeholder: '已投入的資源、對放棄的抗拒…',
  },
  {
    id: '2.17',
    phase: 'phase2',
    section: 'Convergent — 偏誤逐項檢查',
    text: '【月暈效應】你是否因為對某個人的整體印象而過度信任或否定他的提案？',
    purpose: '檢查月暈效應',
    claims: ['C-020'],
    inputType: 'textarea',
    placeholder: '人物印象對判斷的影響…',
  },

  // Phase 2D: Alternatives
  {
    id: '2.18',
    phase: 'phase2',
    section: 'Convergent — 替代方案',
    text: '除了目前的方案，還有哪些替代方案？至少列出 3 個。',
    purpose: '強制考慮替代方案',
    claims: ['C-050'],
    inputType: 'textarea',
    placeholder: '替代方案 A… B… C…',
  },
  {
    id: '2.19',
    phase: 'phase2',
    section: 'Convergent — 替代方案',
    text: '「不做事」也是一個選項嗎？維持現狀的代價是什麼？',
    purpose: '檢查不作為偏誤',
    inputType: 'textarea',
    placeholder: '維持現狀的成本與後果…',
  },
  {
    id: '2.20',
    phase: 'phase2',
    section: 'Convergent — 替代方案',
    text: '是否可以把大決策拆成幾個小決策，分階段執行？',
    purpose: '引入試點/階段性決策',
    claims: ['C-076', 'C-082'],
    inputType: 'textarea',
    placeholder: '可能的分階段方案…',
  },

  // Phase 2E: Premortem
  {
    id: '2.21',
    phase: 'phase2',
    section: 'Convergent — 事前驗屍',
    text: '假設一年後這個決策被執行了，但結果慘敗。請用 5-10 分鐘寫下慘敗的可能原因。',
    purpose: '事前驗屍',
    claims: ['C-045', 'C-046', 'C-047'],
    inputType: 'textarea',
    placeholder: '假設失敗了，最可能的原因是…',
  },
  {
    id: '2.22',
    phase: 'phase2',
    section: 'Convergent — 事前驗屍',
    text: '在這些失敗原因中，哪些是你現在就能預防的？',
    purpose: '將事前驗屍轉化為行動',
    claims: ['C-047'],
    inputType: 'textarea',
    placeholder: '可預防的失敗原因及對策…',
  },

  // Phase 3: Pilot design
  {
    id: '3.1',
    phase: 'phase3',
    section: 'Pilot Design — 試點設計',
    text: '這個方案的最小可測試版本是什麼？',
    purpose: '縮小範圍',
    claims: ['C-076', 'C-082'],
    inputType: 'textarea',
    placeholder: '最小規模的測試方案…',
  },
  {
    id: '3.2',
    phase: 'phase3',
    section: 'Pilot Design — 試點設計',
    text: 'Outcome metrics：試點成功時，你會看到什麼具體結果？',
    purpose: '定義結果指標',
    inputType: 'textarea',
    placeholder: '可觀察的結果指標…',
  },
  {
    id: '3.3',
    phase: 'phase3',
    section: 'Pilot Design — 試點設計',
    text: 'Process metrics：試點過程中，你要追蹤哪些過程指標？',
    purpose: '定義過程指標',
    inputType: 'textarea',
    placeholder: '過程追蹤指標…',
  },
  {
    id: '3.4',
    phase: 'phase3',
    section: 'Pilot Design — 試點設計',
    text: 'Guardrail metrics：哪些指標一旦觸發就必須停止？',
    purpose: '定義護欄指標',
    inputType: 'textarea',
    placeholder: '必須停止的觸發條件…',
  },
  {
    id: '3.5',
    phase: 'phase3',
    section: 'Pilot Design — 試點設計',
    text: 'go threshold：達到什麼條件才擴大實施？',
    purpose: '定義 go 門檻',
    inputType: 'textarea',
    placeholder: '擴大實施的條件…',
  },
  {
    id: '3.6',
    phase: 'phase3',
    section: 'Pilot Design — 試點設計',
    text: 'revise threshold：達到什麼條件要修改方案後再試？',
    purpose: '定義 revise 門檻',
    inputType: 'textarea',
    placeholder: '修改方案的條件…',
  },
  {
    id: '3.7',
    phase: 'phase3',
    section: 'Pilot Design — 試點設計',
    text: 'stop threshold：達到什麼條件必須完全停止？',
    purpose: '定義 stop 門檻',
    inputType: 'textarea',
    placeholder: '完全停止的條件…',
  },
  {
    id: '3.8',
    phase: 'phase3',
    section: 'Pilot Design — 試點設計',
    text: '試點的檢討日期是什麼時候？',
    purpose: '預設檢討時點',
    inputType: 'text',
    placeholder: '例如：2026-09-30',
  },
];

export const PHASE_LABELS: Record<string, string> = {
  phase0: 'Phase 0 — 決策問題界定',
  phase1: 'Phase 1 — Divergent（直覺與假設展開）',
  phase2: 'Phase 2 — Convergent（證據與偏誤檢核）',
  phase3: 'Phase 3 — Pilot Design（試點設計）',
  report: 'Phase 4 — 決策審查報告',
};
